server:
  port: 8080
reverse_proxy:
  remote_url: https://apiuat.kss.com.vn/uat/v1/kos/p
arrango_db:
  endpoint: http://54.169.132.20:8529
  uname: root
  password: openSesame
  db: shortenlink
  tables:
    - url
    - log