version: '3.9'
services:
  arangodb:
    image: arangodb/arangodb:3.9.1
    container_name: arangodb
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
    ports:
      - "8529:8529"
    # volumes:
    #   - docker/database:/var/lib/mysql
  app:
    container_name: url_shortener
    build: .
    volumes:
      - .:/build
    ports:
      - "8081:8000"