name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "building docker"
        docker build . --file Dockerfile --tag trunglv:latest
        docker run -d --name trunglv . --file Dockerfile --tag trunglv:latest
        echo "finish building"
